version: "2"
services:
  app:
    container_name: eatsmart-story
    image: deakinlaunchpad/eatsmart-story-dev
    restart: always

    command: bash -c "npm start"
    ports:
      - "3014:3014"
    
      